---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrm-production
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: hrm-production
          envFrom:
            - configMapRef:
                name: backend-config-file
          env: # Setting Environmental Variables
            - name: host   # Setting Database host address
              value: mysql
            - name: dbname  # Setting Database name
              value: fleetdb
            - name: username  # Setting Database username
              value: root
            - name: password # Setting Database password
              value: root
          # resources:
          #   requests:
          #     cpu: 25m
          #     memory: 300M
          #   limits:
          #     cpu: 50m
          #     memory: 400M
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8090
      targetPort: 8090
      name: backend
      protocol: "TCP"
