apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./configs
images:
  - name: hrm-production
    newName: minhpt10595/hrm-tool:latest
namespace: hrm-production
